version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo_test_14

    ports:
      - "0.0.0.0:8069:8069"
      - "127.0.0.1:6899:6899"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    privileged: true
