FROM debian:jessie
MAINTAINER Halltic eSolutions S.L.

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            node-less \
            python-gevent \
            python-pip \
            python-renderpm \
            python-support \
            python-watchdog \
            python-lxml \
	    && pip install pySocks \
	    && pip install urllib3 \
	    && pip install boto3

