version: '3'
services:
  nginx_13:
    image: nginx
    container_name: nginx_13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/certs:/etc/nginx/ssl/"
    depends_on:
      - odoo
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo__oficial_13
    depends_on:
      - db
    ports:
      - "0.0.0.0:8069:8069"
      - "127.0.0.1:6899:6899"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./conf:/etc/odoo
      - ./odoo_addons_13:/mnt/extra-addons
      - ./odoo/filestore:/var/lib/odoo
      - ./wait-for-psql.py:/usr/local/bin/wait-for-psql.py
    privileged: true
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - NETWORK_ACCESS=internal
    volumes:
      - ./database_13:/var/lib/postgresql/data
